### PR TITLE
Support geometry collection in H3 polyfill

### PR DESCRIPTION
**Pull request by vdelacruzb**

### CODE REVIEW

**Comment by vdelacruzb** [comment]
No performance changes have been applied to this PR maybe in the future we can try to improve it by using a more imperative programming.

**Review by Jesus89 — APPROVED** [review]
LGTM!

I would clarify a bit the notation used in the tests.

**Comment by Jesus89** [comment]
Please, update the changelog and the version number too

**Comment by vdelacruzb** [comment]
- Added a Multipolygon to the GEOMETRYCOLLECTION test.
- Updated the comments as they could be confused.
- Removed the comment on `-- 5 is a...` as the GEOMETRYCOLLECTION is not tata composed of other test geoms anymore.

**Pull request merged**
