### PR TITLE
WIP: Create routing module

### PR DESCRIPTION
**Pull request by francois-baptiste**

### CODE REVIEW

**Comment by vdelacruzb** [comment]
Let's review and merge when there is at least one function. So all the modules that we have in the repo already include some functionalities :).

**Comment by francois-baptiste** [comment]
> Let's review and merge when there is at least one function. So all the modules that we have in the repo already include some functionalities :).

Yeah sure work is in progress!

**Comment by Jesus89** [comment]
Hey, for WIP work there's an option of Draft in GitHub, which is a previous step of the PR.

This particular case is an "advanced" module, so I'll close this PR.

**Comment by francois-baptiste** [comment]
> Hey, for WIP work there's an option of Draft in GitHub, which is a previous step of the PR.

Nice option that gitlab lacked!

**Pull request closed without merging**
