### PR TITLE
Fix st asquadint polyfill

### PR DESCRIPTION
**Pull request by vdelacruzb**
We were getting wrong values in quadint_polyfill, after investigating a bit further I saw that some int parsing were missing.

### CODE REVIEW

**Review by Algunenano — CHANGES_REQUESTED** [review]
The fact that you are changing those number by these numbers gives me basically zero confidence. Can you add some tests that would have failed before and work now, please?

**Comment by vdelacruzb** [comment]
I just added a test that would fail previously. The JS function wasn't returning the same values as the UDF, now it does.

**Review by Jesus89 — COMMENTED** [review]
Looks good. But I have some questions:
- Should we review other functions (S2, H3, ...) to parseInt?
- In this case, should we also parse input params like `quadint`?

**Comment by vdelacruzb** [comment]
> Looks good. But I have some questions:
> 
> * Should we review other functions (S2, H3, ...) to parseInt?
> * In this case, should we also parse input params like `quadint`?

* It would be good to check in another modules yes. I will add it to this review.
* The functions that accept quadint (bbox, parent, children, sibling...) call inside ZXYFromQuadint which already do it.

**Comment by vdelacruzb** [comment]
- Applied changes to a S2 function.
Other functions in placekey and H3 where ok. I have followed the convention that we use in H3 and casting to Number instead of doing parseInt.

**Review by Jesus89 — APPROVED** [review]
LGTM

**Pull request merged**
