### PR TITLE
Feature/ch150219/add st concavehull

### PR DESCRIPTION
**Pull request by vdelacruzb**

### CODE REVIEW

**Review by Jesus89 — APPROVED** [review]
LGTM.

Let's test it in staging

**Review by alex-graciano — APPROVED** [review]
Nice work!

**Comment by Jesus89** [comment]
Working OK in staging :+1:

**Comment by Jesus89** [comment]
@vdelacruzb is the version not updated in the package (1.2.0): code, docs, tests, etc. Could you update it?

**Pull request merged**
