### PR TITLE
Improve CD

### PR DESCRIPTION
**Pull request by Jesus89**
- Add BQ deploy scripts (prod, stag)
- Add SF deploy scripts (prod, stag)

### CODE REVIEW

**Review by vdelacruzb — APPROVED** [review]
Nice, LGTM, let's see if deploys to staging when approved.

Couple questions:
- You were talking about having a different deploy on staging per PR to avoid collisions, I guess it comes later.
- Do you know if it's possible or a good idea to limit merge to CARTO dev team? I'm afraid, that contributors could merge immediately after approval without someone checking staging.

**Review by vdelacruzb — APPROVED** [review]
It looks like, the staging deployment is not taking place after my approval. Let's go for a second test.

**Comment by Jesus89** [comment]
> You were talking about having a different deploy on staging per PR to avoid collisions, I guess it comes later.

Yes.

> Do you know if it's possible or a good idea to limit merge to CARTO dev team? I'm afraid, that contributors could merge immediately after approval without someone checking staging.

Yes. Only core contributors/team members can approve/merge.

> It looks like, the staging deployment is not taking place after my approval

I'll review the GitHub Action trigger.

**Review by Jesus89 — COMMENTED** [review]
Test

**Review by Jesus89 — COMMENTED** [review]
Test

**Review by vdelacruzb — APPROVED** [review]

**Comment by vdelacruzb** [comment]
Awesome it runs de deploy. We still need to fix the crash on deployment and that's it.

**Review by vdelacruzb — APPROVED** [review]

**Comment by Jesus89** [comment]
Cool. Everything configured and it works. So we're done!

**Pull request merged**
